// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// WebAPI is an autogenerated mock type for the WebAPI type
type WebAPI struct {
	mock.Mock
}
