app:
  name: 'User-Service'
  version: '1.0.0'

http:
  port: '9000'
  allowed-origins:
    - 'http://localhost:4200'
    - 'https://micflix-platform.krekels-server.com'
    - 'https://micflix-data.krekels-server.com'

logger:
  log_level: 'debug'
  rollbar_env: 'User-Service'

# postgres:
#   pool_max: 2

# rabbitmq:
#   rpc_server_exchange: 'rpc_server'
#   rpc_client_exchange: 'rpc_client'
