app:
  name: 'User-service'
  version: '1.0.0'

http:
  port: '9000'

logger:
  log_level: 'debug'
  rollbar_env: 'User-service'

# postgres:
#   pool_max: 2

# rabbitmq:
#   rpc_server_exchange: 'rpc_server'
#   rpc_client_exchange: 'rpc_client'

mongodb:
  username : 'Mickey'
  password : '6TTbNyaZvUxXMQA0'
  cluster : 'fontysprojects.b76fa.azure.mongodb.net'
  database : 'Micflix'